package com.example.demo.dao;

import com.example.demo.pojo.Music;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MusicMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Music
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Music
     *
     * @mbg.generated
     */
    int insert(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Music
     *
     * @mbg.generated
     */
    int insertSelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Music
     *
     * @mbg.generated
     */
    Music selectByPrimaryKey(Long Id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Music
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Music
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Music record);

}