package com.example.demo.pojo;

import java.io.Serializable;


public class Music implements Serializable {

    private static final long serialVersionUID = 2854688440125078359L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Music.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Music.music_name
     *
     * @mbg.generated
     */
    private String musicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Music.music_url
     *
     * @mbg.generated
     */
    private String musicUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Music.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Music.id
     *
     * @return the value of Music.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Music.id
     *
     * @param id the value for Music.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Music.music_name
     *
     * @return the value of Music.music_name
     *
     * @mbg.generated
     */
    public String getMusicName() {
        return musicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Music.music_name
     *
     * @param musicName the value for Music.music_name
     *
     * @mbg.generated
     */
    public void setMusicName(String musicName) {
        this.musicName = musicName == null ? null : musicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Music.music_url
     *
     * @return the value of Music.music_url
     *
     * @mbg.generated
     */
    public String getMusicUrl() {
        return musicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Music.music_url
     *
     * @param musicUrl the value for Music.music_url
     *
     * @mbg.generated
     */
    public void setMusicUrl(String musicUrl) {
        this.musicUrl = musicUrl == null ? null : musicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Music.is_delete
     *
     * @return the value of Music.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Music.is_delete
     *
     * @param isDelete the value for Music.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}